name:                properties-file
version:             0.1.0.0
github:              "ashutoshrishi/properties-file"
license:             BSD3
author:              "Rishi Ranjan"
maintainer:          "rishi@cadmus.io"
copyright:           "2019 Rishi Ranjan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ashutoshrishi/properties-file#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- bytestring
- scientific
- text
- unordered-containers

library:
  source-dirs: src

tests:
  properties-file-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - properties-file
    - aeson-pretty
    - hedgehog
    - tasty
    - tasty-discover
    - tasty-golden
    - tasty-hunit
